
/**
* optimizationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* niedziela, 9 grudnia 2018 19:23:10 Czas środkowoeuropejski standardowy
*/

public interface optimizationOperations 
{
  void register (short ip, int timeout, org.omg.CORBA.IntHolder id);
  void hello (int id);
  void best_range (rangeHolder r);
} // interface optimizationOperations
