
/**
* optimization.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* niedziela, 9 grudnia 2018 19:23:10 Czas środkowoeuropejski standardowy
*/

public interface optimization extends optimizationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface optimization
