
/**
* rangeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* niedziela, 9 grudnia 2018 19:23:10 Czas środkowoeuropejski standardowy
*/

public final class rangeHolder implements org.omg.CORBA.portable.Streamable
{
  public range value = null;

  public rangeHolder ()
  {
  }

  public rangeHolder (range initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rangeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rangeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rangeHelper.type ();
  }

}
